
package cn.wind.webservicee.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloserServiceImplService", targetNamespace = "webServices.WebServiceE.wind.cn", wsdlLocation = "http://localhost:8080/webservice/HelloWorld?wsdl")
public class HelloserServiceImplService
    extends Service
{

    private final static URL HELLOSERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HELLOSERSERVICEIMPLSERVICE_QNAME = new QName("webServices.WebServiceE.wind.cn", "HelloserServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice/HelloWorld?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HELLOSERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HelloserServiceImplService() {
        super(__getWsdlLocation(), HELLOSERSERVICEIMPLSERVICE_QNAME);
    }

    public HelloserServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERSERVICEIMPLSERVICE_QNAME, features);
    }

    public HelloserServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERSERVICEIMPLSERVICE_QNAME);
    }

    public HelloserServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERSERVICEIMPLSERVICE_QNAME, features);
    }

    public HelloserServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloserServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHelloSevice
     */
    @WebEndpoint(name = "HelloserServiceImplPort")
    public IHelloSevice getHelloserServiceImplPort() {
        return super.getPort(new QName("webServices.WebServiceE.wind.cn", "HelloserServiceImplPort"), IHelloSevice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloSevice
     */
    @WebEndpoint(name = "HelloserServiceImplPort")
    public IHelloSevice getHelloserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("webServices.WebServiceE.wind.cn", "HelloserServiceImplPort"), IHelloSevice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOSERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HELLOSERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
