server:
  port: 9001
  servlet:
    context-path: /system
spring:
    application:
      name: system
    # 增加数据库连接
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/icloudcourse?characterEncoding=UTF8&autoReconnect=true
      username: courseimooc
      password: 000000


eureka:
  client:
    service-url:
      # 将服务注册到注册中心：增加配置，执行注册中心地址。
      defaultZoone: http://localhost:8761/eureka/

