server:
  port: 9002
  servlet:
    context-path: /business
spring:
    application:
      name: business

eureka:
  client:
    service-url:
      # 将服务注册到注册中心：增加配置，执行注册中心地址。
      defaultZoone: http://localhost:8761/eureka/

