
package cn.wind.webservicee.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHelloSevice", targetNamespace = "webServices.WebServiceE.wind.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHelloSevice {


    /**
     * 
     * @param str
     * @param aa
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "Resultstr", targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "webServices.WebServiceE.wind.cn", className = "cn.wind.webservicee.webservices.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "webServices.WebServiceE.wind.cn", className = "cn.wind.webservicee.webservices.SayResponse")
    public String say(
            @WebParam(name = "str", targetNamespace = "")
                    String str,
            @WebParam(name = "AA", targetNamespace = "")
                    int aa);

}
