server:
  port: 9000

spring:
    application:
      name: gateway
    cloud:
      gateway:
        routes[0]:
          id: system
          uri: http://127.0.0.1:9001
          predicates[0]:
            name: Path
            args[0]: /system/**

eureka:
  client:
    service-url:
      # 将服务注册到注册中心：增加配置，执行注册中心地址。
      defaultZoone: http://localhost:8761/eureka/
