server:
  port: 9000

spring:
    application:
      name: gateway
    cloud:
      gateway:
        routes[0]:
          id: system
          # uri: http://127.0.0.1:9001
          uri: lb://system
          predicates[0]:
            name: Path
            args[0]: /system/**
        routes[1]:
          id: business
          # 若配置的是ip端口号，发布到生产上可能访问不到，即使配置了maven环境，也需要提前知道上线后的端口号，提前配好。
          #所以应尽量避免端口号形式，而应该使用lb:bussiness 形式。
          # uri: http://127.0.0.1:9002
          uri: lb://business
          predicates[0]:
            name: Path
            args[0]: /business/**
        routes[2]:
          id: system
          uri: lb://file
          predicates[0]:
            name: Path
            args[0]: /file/**

eureka:
  client:
    service-url:
      # 将服务注册到注册中心：增加配置，执行注册中心地址。
      defaultZoone: http://localhost:8761/eureka/
