CREATE USER 'courseimooc'@'localhost' IDENTIFIED BY '000000';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `icloudcourse`.* TO 'courseimooc'@'localhost';

GRANT GRANT OPTION ON `icloudcourse`.* TO 'courseimooc'@'localhost';

